<?php

if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
    'key' => 'group_5c7d17e31989e',
    'title' => 'Produkt',
    'fields' => array(
      array(
        'key' => 'field_5c7d1d41a01b2',
        'label' => 'Krátký popis produktu',
        'name' => 'short_description',
        'type' => 'textarea',
        'instructions' => '1-2 věty o tomto produktu',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_5c7d1d6aa01b3',
        'label' => 'Cena',
        'name' => 'price',
        'type' => 'number',
        'instructions' => 'Jednotková cena za kus',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => 'Kč/ks',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5c7d1f09c3f47',
        'label' => 'Minimální objednávka',
        'name' => 'minimal_order',
        'type' => 'number',
        'instructions' => 'Minimální počet kusů produktu, který nabízíte k odběru',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => 'Počet kusů',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5cbf069f3ae2d',
        'label' => 'EAN kód',
        'name' => 'ean',
        'type' => 'text',
        'instructions' => 'Příslušný EAN kód k tomuto produktu, pomůže nám v lepším párování produktů na stránce.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5cc6fbe565ff6',
        'label' => 'Kategorie',
        'name' => 'category',
        'type' => 'taxonomy',
        'instructions' => 'Zvolte si kategorii, do které spadá váš produkt.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'producttaxonomy',
        'field_type' => 'select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 1,
        'load_terms' => 1,
        'return_format' => 'object',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5c7d1db9a01b4',
        'label' => 'Popis produktu',
        'name' => 'description',
        'type' => 'wysiwyg',
        'instructions' => 'Podrobně popište přínos, vlastnosti a funkce produktu.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5c7d1fbf2e01c',
        'label' => 'Velkoobchod',
        'name' => 'related_wholesaler',
        'type' => 'post_object',
        'instructions' => 'Vyberte prosím schválený velkoobchod',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'custom',
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'return_format' => 'object',
        'ui' => 1,
      ),
      array(
        'key' => 'field_5c7d203dd6c7b',
        'label' => 'Obrázek produktu',
        'name' => 'thumbnail',
        'type' => 'image',
        'instructions' => 'Vložte popisné obrázky produktu, maximální velikost souboru 2 MB.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'wholesaler-logo-thumb',
        'library' => 'uploadedTo',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => 2,
        'mime_types' => '',
      ),
      array(
        'key' => 'field_5c7d1f71c3f48',
        'label' => 'Galerie produktu',
        'name' => 'gallery',
        'type' => 'gallery',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'min' => '',
        'max' => 4,
        'insert' => 'append',
        'library' => 'uploadedTo',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => 2,
        'mime_types' => '',
        'return_format' => 'array',
        'preview_size' => 'medium',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'product',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

endif;