<?php

add_action( 'acf/init', function () {

  acf_add_local_field_group(array(
    'key' => 'group_5b7a9311bf16f',
    'title' => 'Nastavení homepage',
    'fields' => array(
      array(
        'key' => 'field_5b7a93705a570',
        'label' => 'Příspěvky',
        'name' => 'homepage_posts_ids',
        'type' => 'relationship',
        'instructions' => 'Zvolte prosím 2 články',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'post',
          1 => 'page',
        ),
        'taxonomy' => array(
        ),
        'filters' => array(
          0 => 'search',
        ),
        'elements' => '',
        'min' => '',
        'max' => 2,
        'return_format' => 'id',
      ),
      array(
        'key' => 'field_5b7a93b95a571',
        'label' => 'Komu jsme už pomohli',
        'name' => 'homepage_testimonial',
        'type' => 'repeater',
        'instructions' => 'Napište prosím 3 doporučení',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 3,
        'layout' => 'row',
        'button_label' => 'Přidat doporučení',
        'sub_fields' => array(
          array(
            'key' => 'field_5b7a94015a572',
            'label' => 'Jméno',
            'name' => 'name',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5b7a94085a573',
            'label' => 'Fotografie',
            'name' => 'image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
          array(
            'key' => 'field_5b7a941f5a574',
            'label' => 'Pozice',
            'name' => 'position',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5b7a942c5a575',
            'label' => 'Text doporučení',
            'name' => 'text',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 5,
            'new_lines' => 'wpautop',
          ),
        ),
      ),
      array(
        'key' => 'field_5ba8db67198f2',
        'label' => 'FAQ pro velkoobchody',
        'name' => 'homepage_faq_wholesaler_post',
        'type' => 'page_link',
        'instructions' => 'Zvolte článek, ve kterém jsou umístěny kotvy, na které chcete odkazovat',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'allow_archives' => 1,
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5ba8dbfb198f3',
        'label' => 'FAQ pro velkoobchody – kotvy',
        'name' => 'homepage_faq_wholesaler_anchors',
        'type' => 'repeater',
        'instructions' => 'Přidejte kotvy odpovídající nadpisům ve zvoleném článku.
  Nezapomeňte u nadpisů přidat HTML atribut id.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Přidat kotvu',
        'sub_fields' => array(
          array(
            'key' => 'field_5ba8dc1f198f4',
            'label' => 'Titulek',
            'name' => 'title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ba8dc5f198f5',
            'label' => 'Kotva',
            'name' => 'anchor',
            'type' => 'text',
            'instructions' => 'Zadejte id HTML elementu, na který chcete odkázat',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '#',
            'append' => '',
            'maxlength' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_5ba8e4675d89f',
        'label' => 'FAQ pro maloobchody',
        'name' => 'homepage_faq_retail_post',
        'type' => 'page_link',
        'instructions' => 'Zvolte článek, ve kterém jsou umístěny kotvy, na které chcete odkazovat',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'allow_archives' => 1,
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5ba8e4795d8a0',
        'label' => 'FAQ pro maloobchody – kotvy',
        'name' => 'homepage_faq_retail_anchors',
        'type' => 'repeater',
        'instructions' => 'Přidejte kotvy odpovídající nadpisům ve zvoleném článku.
  Nezapomeňte u nadpisů přidat HTML atribut id.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Přidat kotvu',
        'sub_fields' => array(
          array(
            'key' => 'field_5ba8e4795d8a1',
            'label' => 'Titulek',
            'name' => 'title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ba8e4795d8a2',
            'label' => 'Kotva',
            'name' => 'anchor',
            'type' => 'text',
            'instructions' => 'Zadejte id HTML elementu, na který chcete odkázat',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '#',
            'append' => '',
            'maxlength' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_5be44b5681477',
        'label' => 'Fakový počet poptávek',
        'name' => 'fake_message_number',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5be44b7a81478',
        'label' => 'Maximální konstanta navýšení fakových poptávek',
        'name' => 'fake_message_max_increase_constant',
        'type' => 'number',
        'instructions' => 'Fakový počet poptávek se každou hodinu navýší o náhodně vygenerované celé číslo v rozsahu 0 až [tato-hodnota]. Průměrně se tedy počet navýší o [tato-hodnota]/2. Např. pokud zadáte číslo 10, tak se v průměru počet fakových poptávek navýší o 5.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-homepage',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5a971a73dc55a',
    'title' => 'Nastavení mailingu',
    'fields' => array(
      array(
        'key' => 'field_5a971a8cbed13',
        'label' => 'Odesílatel e-mailů',
        'name' => 'email_from',
        'type' => 'text',
        'instructions' => 'Ve tvaru "Jméno &lt;email&gt;"',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b802ebc11de1',
        'label' => 'Příjemci e-mailu s upozorněním o čekajícím velkoobchodu, produktu nebo čekající nabídce',
        'name' => 'pending_email_recipients',
        'type' => 'user',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'role' => '',
        'allow_null' => 0,
        'multiple' => 1,
        'return_format' => 'array',
      ),
      array(
        'key' => 'field_5a971a73e1497',
        'label' => 'Předmět e-mailu se zprávou pro velkoobchod',
        'name' => 'wholesaler_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a971a73e149e',
        'label' => 'Tělo e-mailu se zprávou pro velkoobchod',
        'name' => 'wholesaler_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %contact_name%, %contact_email%, %contact_message%\' a %wholesaler_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5ccd5e38be85b',
        'label' => 'Předmět e-mailu se zájmem o produkt',
        'name' => 'product_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5ccd5e3cbe85c',
        'label' => 'Tělo e-mailu se zájmem o produkt',
        'name' => 'product_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %contact_name%, %contact_email%, %contact_message%\' %wholesaler_name% a %product_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5a971a73e14a5',
        'label' => 'Předmět potvrzovacího e-mailu pro odesílatele',
        'name' => 'retailer_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a971a73e14ac',
        'label' => 'Tělo potvrzovacího e-mailu pro odesílatele',
        'name' => 'retailer_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %contact_name%, %contact_email%, %contact_message%\' a %wholesaler_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5a98129ba2bfb',
        'label' => 'Předmět e-mailu s pro nového uživatele',
        'name' => 'welcome_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a9812a2a2bfc',
        'label' => 'Tělo e-mailu pro nového uživatele',
        'name' => 'welcome_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %username% a %set_password_url%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5d230d9e7b67d',
        'label' => 'Předmět e-mailu pro nového uživatele založeného operátorem',
        'name' => 'operator_welcome_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5d230d987b67c',
        'label' => 'Tělo e-mailu pro nového uživatele založeného operátorem',
        'name' => 'operator_welcome_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %username% a %approving_url%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5d25b6af73a62',
        'label' => 'Odesílatel e-mailů s odkazem na registarci velkoobchodu',
        'name' => 'operator_registration_email_from',
        'type' => 'text',
        'instructions' => 'Ve tvaru "Jméno &lt;email&gt;"',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5d25b6fe73a63',
        'label' => 'Předmět e-mailu s odkazem na registraci velkoobchodu',
        'name' => 'operator_registration_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5d25b70173a64',
        'label' => 'Tělo e-mailu s odkazem na registraci velkoobchodu',
        'name' => 'operator_registration_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %registration_url%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5b802e5b11ddf',
        'label' => 'Předmět e-mailu s upozorněním o čekajícím velkoobchodu',
        'name' => 'pending_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b802e8711de0',
        'label' => 'Tělo e-mailu s upozorněním o čekajícím velkoobchodu',
        'name' => 'pending_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %wholesaler_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5c94db9de17d7',
        'label' => 'Předmět e-mailu s upozorněním o čekajícím produktu',
        'name' => 'pending_product_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5c94dba3e17d8',
        'label' => 'Tělo e-mailu s upozorněním o čekajícím produktu',
        'name' => 'pending_product_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %product_name% %wholesaler_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5cc95a1696108',
        'label' => 'Předmět e-mailu s upozorněním o zveřejněném velkoobchodu',
        'name' => 'publish_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5cc95a1b96109',
        'label' => 'Tělo e-mailu s upozorněním o zveřejněném velkoobchodu',
        'name' => 'publish_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %wholesaler_name%, %wholesaler_url%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-mailing',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5e451ef871db5',
    'title' => 'Nastavení stránky přihlášení',
    'fields' => array(
      array(
        'key' => 'field_5e451f1681722',
        'label' => 'Výhody',
        'name' => 'login-screen-benefits',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'block',
        'button_label' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_5e451f6781723',
            'label' => 'Font Awesome class',
            'name' => 'icon-class',
            'type' => 'text',
            'instructions' => 'Dle https://fontawesome.com/icons?d=gallery',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5e451f9181724',
            'label' => 'Název',
            'name' => 'title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5e451f9981725',
            'label' => 'Text',
            'name' => 'text',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-prihlaseni',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));
  
  acf_add_local_field_group(array(
    'key' => 'group_5b76a52eb5c0a',
    'title' => 'Obecné nastavení',
    'fields' => array(
      array(
        'key' => 'field_5b76a53cd67e5',
        'label' => 'Popis stránky s výpisem velkoobchodů',
        'name' => 'archive_description',
        'type' => 'wysiwyg',
        'instructions' => 'Popis se zobrazí pod výpisem velkoobchodů. Pokud bude ve filtrování zvolena právě jedna kategorie, tak se zvolí popis této kategorie.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5c864182e51a6',
        'label' => 'Popis stránky s výpisem produktů',
        'name' => 'archive_product_description',
        'type' => 'wysiwyg',
        'instructions' => 'Popis se zobrazí pod výpisem produktů.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5b804b31dfd08',
        'label' => 'Článek v banneru ve výpisu velkoobchodů',
        'name' => 'archive_post',
        'type' => 'post_object',
        'instructions' => 'Článek se zobrazí uprostřed seznamu s velkoobchody.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'post',
          1 => 'page',
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'return_format' => 'object',
        'ui' => 1,
      ),
      array(
        'key' => 'field_5c94b0a31693d',
        'label' => 'Maximální počet produktů',
        'name' => 'product_limit',
        'type' => 'number',
        'instructions' => 'Maximální možný počet produktů, které může uživatel vytvořit',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5ced28b2e190a',
        'label' => 'Kategorie velkoobchodů 18+',
        'name' => 'age_test_wholesaler_categories',
        'type' => 'taxonomy',
        'instructions' => 'Zvolte kategorie velkoobchodů, u kterých bude uživatelům zobrazeno pop-up okno s potvrzením 18+ věku.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'customtaxonomy',
        'field_type' => 'multi_select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'id',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5ced2afac5faf',
        'label' => 'Kategorie produktů 18+',
        'name' => 'age_test_product_categories',
        'type' => 'taxonomy',
        'instructions' => 'Zvolte kategorie produktů, u kterých bude uživatelům zobrazeno pop-up okno s potvrzením 18+ věku.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'producttaxonomy',
        'field_type' => 'multi_select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'id',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5d39bc72a63de',
        'label' => 'Přístup do administrace',
        'name' => 'disable_admin',
        'type' => 'true_false',
        'instructions' => 'Zaškrtněte, pokud chcete uživatelům zamezit přístup do administrace. Toto nastavení se netýká administrátorů.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => 'Zamezit přístup do administrace',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-obecne',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

} );