<?php

if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
    'key' => 'group_5c2e07a1bb0df',
    'title' => 'Akční nabídka',
    'fields' => array(
      array(
        'key' => 'field_5c2e15a1be4ee',
        'label' => 'Popis',
        'name' => 'description',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5c2e15d2be4ef',
        'label' => 'Cena',
        'name' => 'price',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => 'Kč',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5c45b658f24e8',
        'label' => 'Množství',
        'name' => 'amount',
        'type' => 'text',
        'instructions' => 'Vyplňte prosím množství nebo jednotku, za kterou je udávána cena. Množství bude zobrazeno společně s cenou, např. "2000 Kč / ks".',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => 'Např. "ks", "5 ks"...',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5c2e1640be4f0',
        'label' => 'Náhledový obrázek',
        'name' => 'image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'wholesaler-logo-thumb',
        'library' => 'uploadedTo',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_5c2e16dabe4f1',
        'label' => 'Velkoobchod',
        'name' => 'related_wholesaler',
        'type' => 'post_object',
        'instructions' => 'Vyberte prosím schválený velkoobchod',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'custom',
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'return_format' => 'object',
        'ui' => 1,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'special_offer',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5cd41ee6a3708',
    'title' => 'Hromadný import produktů',
    'fields' => array(
      array(
        'key' => 'field_5cd568b25d2b9',
        'label' => 'Velkoobchod',
        'name' => 'related_wholesaler',
        'type' => 'post_object',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'custom',
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'return_format' => 'object',
        'ui' => 1,
      ),
      array(
        'key' => 'field_5cd41ef65e4d4',
        'label' => 'CSV soubor',
        'name' => 'product_import_file',
        'type' => 'file',
        'instructions' => 'Soubor musí mít kódování Windows-1250 (CP-1250)',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'uploadedTo',
        'min_size' => '',
        'max_size' => 2,
        'mime_types' => 'csv',
      ),
      array(
        'key' => 'field_5cd56a30b38fb',
        'label' => 'Kategorie',
        'name' => 'product_category',
        'type' => 'taxonomy',
        'instructions' => 'Vyberte kategorii, do které chcete hromadně zařadit produkty. Toto nastavení bude ignorováno pokud, má produkt vyplněnou položku <code>category</code>',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'producttaxonomy',
        'field_type' => 'select',
        'allow_null' => 1,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'id',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5cdbfcfac2c59',
        'label' => 'Odeslat ke schválení importované produkty',
        'name' => 'set_pending_status',
        'type' => 'true_false',
        'instructions' => 'Ke schválení se odešlou produkty, které mají vyplněny položky: <code>name</code>, <code>description</code>, <code>shortDescription</code>, <code>image</code> a <code>category</code>. Ostatní produkty budou uloženy jako koncept. Položka <code>category</code> nemusí být vyplněna, pokud je vybrána hromadná kategorie.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => 'Odeslat ke schválení',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'product-import',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'field',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5b5ec83fc69b8',
    'title' => 'Kontaktní údaje',
    'fields' => array(
      array(
        'key' => 'field_5b5ec9b4052f8',
        'label' => 'Ulice a č. p.',
        'name' => 'street',
        'type' => 'text',
        'instructions' => 'Např. "Dvořeckého 628/8"',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b5eca63052f9',
        'label' => 'Město',
        'name' => 'city',
        'type' => 'text',
        'instructions' => 'Např. "Praha 6"',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b5eca9d052fa',
        'label' => 'PSČ',
        'name' => 'zip',
        'type' => 'text',
        'instructions' => 'Např. „12300“.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5bbdc26030686',
        'label' => 'Země',
        'name' => 'country',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'cz' => 'Česká republika',
          'sk' => 'Slovensko',
        ),
        'default_value' => array(
          0 => 'cz',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'array',
        'ajax' => 0,
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5b5ed2ca0a22d',
        'label' => 'Kraj',
        'name' => 'region',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_5bbdc26030686',
              'operator' => '==',
              'value' => 'cz',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          0 => 'Hlavní město Praha',
          1 => 'Jihočeský kraj',
          2 => 'Jihomoravský kraj',
          3 => 'Karlovarský kraj',
          4 => 'Kraj Vysočina',
          5 => 'Královéhradecký kraj',
          6 => 'Liberecký kraj',
          7 => 'Moravskoslezský kraj',
          8 => 'Olomoucký kraj',
          9 => 'Pardubický kraj',
          10 => 'Plzeňský kraj',
          11 => 'Středočeský kraj',
          12 => 'Ústecký kraj',
          13 => 'Zlínský kraj',
        ),
        'default_value' => array(
        ),
        'allow_null' => 1,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'array',
        'ajax' => 0,
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5bbdc19430685',
        'label' => 'Kraj',
        'name' => 'region',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_5bbdc26030686',
              'operator' => '==',
              'value' => 'sk',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          14 => 'Bratislavský kraj',
          15 => 'Trnavský kraj',
          16 => 'Trenčínský kraj',
          17 => 'Nitranský kraj',
          18 => 'Žilinský kraj',
          19 => 'Banskobystrický kraj',
          20 => 'Prešovský kraj',
          21 => 'Košický kraj',
        ),
        'default_value' => array(
        ),
        'allow_null' => 1,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'array',
        'ajax' => 0,
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5b5ecaf4052fb',
        'label' => 'IČ',
        'name' => 'in',
        'type' => 'text',
        'instructions' => 'Např. „28935675“.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b5ecc9d052fc',
        'label' => 'DIČ',
        'name' => 'tin',
        'type' => 'text',
        'instructions' => 'Např. „CZ28935675“.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b5eccbb052fd',
        'label' => 'Web',
        'name' => 'website',
        'type' => 'text',
        'instructions' => 'URL adresa vašeho webu. Např. „https://www.obchodiste.cz“',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b5ecd01052fe',
        'label' => 'Facebook',
        'name' => 'facebook',
        'type' => 'url',
        'instructions' => 'Adresa na váš případný Facebook profil. Např. „https://www.facebook.com/obchodiste/“',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5b5ecd0f052ff',
        'label' => 'Twitter',
        'name' => 'twitter',
        'type' => 'url',
        'instructions' => 'Adresa na váš případný Twitter profil. Např. „https://twitter.com/shoptet“.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5b854f2feaf16',
        'label' => 'Instagram',
        'name' => 'instagram',
        'type' => 'url',
        'instructions' => 'Adresa na váš případný Instagram profil. Např. „https://www.instagram.com/shoptet.cz“.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5b5ed8dcce814',
        'label' => 'Logo',
        'name' => 'logo',
        'type' => 'image',
        'instructions' => 'Doporučujeme nahrát logo o velikosti alespoň 600 x 315 px. Nejlépe však 1200 x 630 px a více.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'wholesaler-logo-thumb',
        'library' => 'uploadedTo',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => 2,
        'mime_types' => '',
      ),
      array(
        'key' => 'field_5b86c6c02b205',
        'label' => 'E-shop na Shoptetu',
        'name' => 'is_shoptet',
        'type' => 'true_false',
        'instructions' => 'Provozujete svůj e-shop na Shoptet řešení?',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => 'Provozuji e-shop na Shoptetu',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'custom',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'field',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5b7a9311bf16f',
    'title' => 'Nastavení homepage',
    'fields' => array(
      array(
        'key' => 'field_5b7a93705a570',
        'label' => 'Příspěvky',
        'name' => 'homepage_posts_ids',
        'type' => 'relationship',
        'instructions' => 'Zvolte prosím 2 články',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'post',
          1 => 'page',
        ),
        'taxonomy' => array(
        ),
        'filters' => array(
          0 => 'search',
        ),
        'elements' => '',
        'min' => '',
        'max' => 2,
        'return_format' => 'id',
      ),
      array(
        'key' => 'field_5b7a93b95a571',
        'label' => 'Komu jsme už pomohli',
        'name' => 'homepage_testimonial',
        'type' => 'repeater',
        'instructions' => 'Napište prosím 3 doporučení',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 3,
        'layout' => 'row',
        'button_label' => 'Přidat doporučení',
        'sub_fields' => array(
          array(
            'key' => 'field_5b7a94015a572',
            'label' => 'Jméno',
            'name' => 'name',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5b7a94085a573',
            'label' => 'Fotografie',
            'name' => 'image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
          array(
            'key' => 'field_5b7a941f5a574',
            'label' => 'Pozice',
            'name' => 'position',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5b7a942c5a575',
            'label' => 'Text doporučení',
            'name' => 'text',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 5,
            'new_lines' => 'wpautop',
          ),
        ),
      ),
      array(
        'key' => 'field_5ba8db67198f2',
        'label' => 'FAQ pro velkoobchody',
        'name' => 'homepage_faq_wholesaler_post',
        'type' => 'page_link',
        'instructions' => 'Zvolte článek, ve kterém jsou umístěny kotvy, na které chcete odkazovat',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'allow_archives' => 1,
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5ba8dbfb198f3',
        'label' => 'FAQ pro velkoobchody – kotvy',
        'name' => 'homepage_faq_wholesaler_anchors',
        'type' => 'repeater',
        'instructions' => 'Přidejte kotvy odpovídající nadpisům ve zvoleném článku.
  Nezapomeňte u nadpisů přidat HTML atribut id.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Přidat kotvu',
        'sub_fields' => array(
          array(
            'key' => 'field_5ba8dc1f198f4',
            'label' => 'Titulek',
            'name' => 'title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ba8dc5f198f5',
            'label' => 'Kotva',
            'name' => 'anchor',
            'type' => 'text',
            'instructions' => 'Zadejte id HTML elementu, na který chcete odkázat',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '#',
            'append' => '',
            'maxlength' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_5ba8e4675d89f',
        'label' => 'FAQ pro maloobchody',
        'name' => 'homepage_faq_retail_post',
        'type' => 'page_link',
        'instructions' => 'Zvolte článek, ve kterém jsou umístěny kotvy, na které chcete odkazovat',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'allow_archives' => 1,
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5ba8e4795d8a0',
        'label' => 'FAQ pro maloobchody – kotvy',
        'name' => 'homepage_faq_retail_anchors',
        'type' => 'repeater',
        'instructions' => 'Přidejte kotvy odpovídající nadpisům ve zvoleném článku.
  Nezapomeňte u nadpisů přidat HTML atribut id.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Přidat kotvu',
        'sub_fields' => array(
          array(
            'key' => 'field_5ba8e4795d8a1',
            'label' => 'Titulek',
            'name' => 'title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5ba8e4795d8a2',
            'label' => 'Kotva',
            'name' => 'anchor',
            'type' => 'text',
            'instructions' => 'Zadejte id HTML elementu, na který chcete odkázat',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '#',
            'append' => '',
            'maxlength' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_5be44b5681477',
        'label' => 'Fakový počet poptávek',
        'name' => 'fake_message_number',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5be44b7a81478',
        'label' => 'Maximální konstanta navýšení fakových poptávek',
        'name' => 'fake_message_max_increase_constant',
        'type' => 'number',
        'instructions' => 'Fakový počet poptávek se každou hodinu navýší o náhodně vygenerované celé číslo v rozsahu 0 až [tato-hodnota]. Průměrně se tedy počet navýší o [tato-hodnota]/2. Např. pokud zadáte číslo 10, tak se v průměru počet fakových poptávek navýší o 5.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-homepage',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5a971a73dc55a',
    'title' => 'Nastavení mailingu',
    'fields' => array(
      array(
        'key' => 'field_5a971a8cbed13',
        'label' => 'Odesílatel e-mailů',
        'name' => 'email_from',
        'type' => 'text',
        'instructions' => 'Ve tvaru "Jméno &lt;email&gt;"',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b802ebc11de1',
        'label' => 'Příjemci e-mailu s upozorněním o čekajícím velkoobchodu, produktu nebo čekající nabídce',
        'name' => 'pending_email_recipients',
        'type' => 'user',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'role' => '',
        'allow_null' => 0,
        'multiple' => 1,
        'return_format' => 'array',
      ),
      array(
        'key' => 'field_5a971a73e1497',
        'label' => 'Předmět e-mailu se zprávou pro velkoobchod',
        'name' => 'wholesaler_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a971a73e149e',
        'label' => 'Tělo e-mailu se zprávou pro velkoobchod',
        'name' => 'wholesaler_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %contact_name%, %contact_email%, %contact_message%\' a %wholesaler_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5ccd5e38be85b',
        'label' => 'Předmět e-mailu se zájmem o produkt',
        'name' => 'product_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5ccd5e3cbe85c',
        'label' => 'Tělo e-mailu se zájmem o produkt',
        'name' => 'product_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %contact_name%, %contact_email%, %contact_message%\' %wholesaler_name% a %product_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5a971a73e14a5',
        'label' => 'Předmět potvrzovacího e-mailu pro odesílatele',
        'name' => 'retailer_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a971a73e14ac',
        'label' => 'Tělo potvrzovacího e-mailu pro odesílatele',
        'name' => 'retailer_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %contact_name%, %contact_email%, %contact_message%\' a %wholesaler_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5a98129ba2bfb',
        'label' => 'Předmět e-mailu s pro nového uživatele',
        'name' => 'welcome_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5a9812a2a2bfc',
        'label' => 'Tělo e-mailu pro nového uživatele',
        'name' => 'welcome_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %username% a %set_password_url%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5d230d9e7b67d',
        'label' => 'Předmět e-mailu pro nového uživatele založeného operátorem',
        'name' => 'operator_welcome_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5d230d987b67c',
        'label' => 'Tělo e-mailu pro nového uživatele založeného operátorem',
        'name' => 'operator_welcome_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %username% a %approving_url%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5d25b6af73a62',
        'label' => 'Odesílatel e-mailů s odkazem na registarci velkoobchodu',
        'name' => 'operator_registration_email_from',
        'type' => 'text',
        'instructions' => 'Ve tvaru "Jméno &lt;email&gt;"',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5d25b6fe73a63',
        'label' => 'Předmět e-mailu s odkazem na registraci velkoobchodu',
        'name' => 'operator_registration_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5d25b70173a64',
        'label' => 'Tělo e-mailu s odkazem na registraci velkoobchodu',
        'name' => 'operator_registration_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %registration_url%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5b802e5b11ddf',
        'label' => 'Předmět e-mailu s upozorněním o čekajícím velkoobchodu',
        'name' => 'pending_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b802e8711de0',
        'label' => 'Tělo e-mailu s upozorněním o čekajícím velkoobchodu',
        'name' => 'pending_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %wholesaler_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5c409947d1fbc',
        'label' => 'Předmět e-mailu s upozorněním o čekající nabídce',
        'name' => 'pending_special_offer_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5c409949d1fbd',
        'label' => 'Tělo e-mailu s upozorněním o čekající nabídce',
        'name' => 'pending_special_offer_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %offer_name%	%wholesaler_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5c94db9de17d7',
        'label' => 'Předmět e-mailu s upozorněním o čekajícím produktu',
        'name' => 'pending_product_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5c94dba3e17d8',
        'label' => 'Tělo e-mailu s upozorněním o čekajícím produktu',
        'name' => 'pending_product_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %product_name% %wholesaler_name%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5cc95a1696108',
        'label' => 'Předmět e-mailu s upozorněním o zveřejněném velkoobchodu',
        'name' => 'publish_email_subject',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5cc95a1b96109',
        'label' => 'Tělo e-mailu s upozorněním o zveřejněném velkoobchodu',
        'name' => 'publish_email_body',
        'type' => 'wysiwyg',
        'instructions' => 'Je možné využít následující proměnné: %wholesaler_name%, %wholesaler_url%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-mailing',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5e451ef871db5',
    'title' => 'Nastavení stránky přihlášení',
    'fields' => array(
      array(
        'key' => 'field_5e451f1681722',
        'label' => 'Výhody',
        'name' => 'login-screen-benefits',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'block',
        'button_label' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_5e451f6781723',
            'label' => 'Font Awesome class',
            'name' => 'icon-class',
            'type' => 'text',
            'instructions' => 'Dle https://fontawesome.com/icons?d=gallery',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5e451f9181724',
            'label' => 'Název',
            'name' => 'title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5e451f9981725',
            'label' => 'Text',
            'name' => 'text',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-prihlaseni',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));
  
  acf_add_local_field_group(array(
    'key' => 'group_5b76a52eb5c0a',
    'title' => 'Obecné nastavení',
    'fields' => array(
      array(
        'key' => 'field_5b76a53cd67e5',
        'label' => 'Popis stránky s výpisem velkoobchodů',
        'name' => 'archive_description',
        'type' => 'wysiwyg',
        'instructions' => 'Popis se zobrazí pod výpisem velkoobchodů. Pokud bude ve filtrování zvolena právě jedna kategorie, tak se zvolí popis této kategorie.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5c3dec3252fb9',
        'label' => 'Popis stránky s výpisem akčních nabídek',
        'name' => 'archive_special_offer_description',
        'type' => 'wysiwyg',
        'instructions' => 'Popis se zobrazí pod výpisem akčních nabídek.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5c864182e51a6',
        'label' => 'Popis stránky s výpisem produktů',
        'name' => 'archive_product_description',
        'type' => 'wysiwyg',
        'instructions' => 'Popis se zobrazí pod výpisem produktů.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5b804b31dfd08',
        'label' => 'Článek v banneru ve výpisu velkoobchodů',
        'name' => 'archive_post',
        'type' => 'post_object',
        'instructions' => 'Článek se zobrazí uprostřed seznamu s velkoobchody.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'post',
          1 => 'page',
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'return_format' => 'object',
        'ui' => 1,
      ),
      array(
        'key' => 'field_5c4093c5bb5ba',
        'label' => 'Maximální počet akčních nabídek',
        'name' => 'special_offer_limit',
        'type' => 'number',
        'instructions' => 'Maximální možný počet akčních nabídek, které může uživatel vytvořit',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5c94b0a31693d',
        'label' => 'Maximální počet produktů',
        'name' => 'product_limit',
        'type' => 'number',
        'instructions' => 'Maximální možný počet produktů, které může uživatel vytvořit',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5cd43b5f6c588',
        'label' => 'Popis stránky pro import produktů',
        'name' => 'product_import_description',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5ce50f7500ecf',
        'label' => 'Počet obrázků ke zpracování při jedné iteraci cronu',
        'name' => 'product_image_sync_count',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5ced28b2e190a',
        'label' => 'Kategorie velkoobchodů 18+',
        'name' => 'age_test_wholesaler_categories',
        'type' => 'taxonomy',
        'instructions' => 'Zvolte kategorie velkoobchodů, u kterých bude uživatelům zobrazeno pop-up okno s potvrzením 18+ věku.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'customtaxonomy',
        'field_type' => 'multi_select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'id',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5ced2afac5faf',
        'label' => 'Kategorie produktů 18+',
        'name' => 'age_test_product_categories',
        'type' => 'taxonomy',
        'instructions' => 'Zvolte kategorie produktů, u kterých bude uživatelům zobrazeno pop-up okno s potvrzením 18+ věku.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'producttaxonomy',
        'field_type' => 'multi_select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'id',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5d39bc72a63de',
        'label' => 'Přístup do administrace',
        'name' => 'disable_admin',
        'type' => 'true_false',
        'instructions' => 'Zaškrtněte, pokud chcete uživatelům zamezit přístup do administrace. Toto nastavení se netýká administrátorů.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => 'Zamezit přístup do administrace',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-obecne',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5c7d17e31989e',
    'title' => 'Produkt',
    'fields' => array(
      array(
        'key' => 'field_5c7d1d41a01b2',
        'label' => 'Krátký popis produktu',
        'name' => 'short_description',
        'type' => 'textarea',
        'instructions' => '1-2 věty o tomto produktu',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_5c7d1d6aa01b3',
        'label' => 'Cena',
        'name' => 'price',
        'type' => 'number',
        'instructions' => 'Jednotková cena za kus',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => 'Kč/ks',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5c7d1f09c3f47',
        'label' => 'Minimální objednávka',
        'name' => 'minimal_order',
        'type' => 'number',
        'instructions' => 'Minimální počet kusů produktu, který nabízíte k odběru',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => 'Počet kusů',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5cbf069f3ae2d',
        'label' => 'EAN kód',
        'name' => 'ean',
        'type' => 'text',
        'instructions' => 'Příslušný EAN kód k tomuto produktu, pomůže nám v lepším párování produktů na stránce.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5cc6fbe565ff6',
        'label' => 'Kategorie',
        'name' => 'category',
        'type' => 'taxonomy',
        'instructions' => 'Zvolte si kategorii, do které spadá váš produkt.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'producttaxonomy',
        'field_type' => 'select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 1,
        'load_terms' => 1,
        'return_format' => 'object',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5c7d1db9a01b4',
        'label' => 'Popis produktu',
        'name' => 'description',
        'type' => 'wysiwyg',
        'instructions' => 'Podrobně popište přínos, vlastnosti a funkce produktu.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5c7d1fbf2e01c',
        'label' => 'Velkoobchod',
        'name' => 'related_wholesaler',
        'type' => 'post_object',
        'instructions' => 'Vyberte prosím schválený velkoobchod',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'custom',
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'return_format' => 'object',
        'ui' => 1,
      ),
      array(
        'key' => 'field_5c7d203dd6c7b',
        'label' => 'Obrázek produktu',
        'name' => 'thumbnail',
        'type' => 'image',
        'instructions' => 'Vložte popisné obrázky produktu, maximální velikost souboru 2 MB.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'wholesaler-logo-thumb',
        'library' => 'uploadedTo',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => 2,
        'mime_types' => '',
      ),
      array(
        'key' => 'field_5c7d1f71c3f48',
        'label' => 'Galerie produktu',
        'name' => 'gallery',
        'type' => 'gallery',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'min' => '',
        'max' => 4,
        'insert' => 'append',
        'library' => 'uploadedTo',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => 2,
        'mime_types' => '',
        'return_format' => 'array',
        'preview_size' => 'medium',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'product',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5ce3e4a3d5c37',
    'title' => 'Synchronizace',
    'fields' => array(
      array(
        'key' => 'field_5ce3e4b8de17c',
        'label' => 'Produkt',
        'name' => 'product',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'product',
        ),
        'taxonomy' => array(
        ),
        'filters' => array(
          0 => 'search',
        ),
        'elements' => '',
        'min' => '',
        'max' => '',
        'return_format' => 'object',
      ),
      array(
        'key' => 'field_5ce3e5a3de17d',
        'label' => 'URL obrázku',
        'name' => 'url',
        'type' => 'url',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5ce3f7fcafa38',
        'label' => 'Thumbnail produktu',
        'name' => 'is_thumbnail',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => 'Obrázek je thumbnail produktu',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_5ce5161ab8c70',
        'label' => 'Pokusy stažení',
        'name' => 'attemps',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'sync',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5d39e3967a178',
    'title' => 'Velkoobchod – hlavní',
    'fields' => array(
      array(
        'key' => 'field_5d39e3b8467ea',
        'label' => 'Název projektu',
        'name' => 'project_title',
        'type' => 'text',
        'instructions' => 'Zadejte název projektu, pod kterým vás znají zákazníci. Např. „Obchodiště“',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'custom',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5b6c3e4e8cff0',
    'title' => 'Zpráva',
    'fields' => array(
      array(
        'key' => 'field_5b6c3e6e57fe7',
        'label' => 'E-mail',
        'name' => 'email',
        'type' => 'email',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_5b6c3e8657fe8',
        'label' => 'Zpráva',
        'name' => 'message',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
      ),
      array(
        'key' => 'field_5b6c3e9f57fe9',
        'label' => 'Velkoobchod',
        'name' => 'wholesaler',
        'type' => 'post_object',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'custom',
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'return_format' => 'object',
        'ui' => 1,
      ),
      array(
        'key' => 'field_5ccd577bb0243',
        'label' => 'Produkt',
        'name' => 'product',
        'type' => 'post_object',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'product',
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'return_format' => 'object',
        'ui' => 1,
      ),
      array(
        'key' => 'field_5c89340ea4520',
        'label' => 'IP',
        'name' => 'ip',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5c896e68b2155',
        'label' => 'Spam',
        'name' => 'spam',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_5ccd5792b0244',
        'label' => 'Zpráva odeslaná kontaktní osobě velkoobchodu',
        'name' => 'sent_message',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'wholesaler_message',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5b5ed46570d96',
    'title' => 'Kontaktní osoba',
    'fields' => array(
      array(
        'key' => 'field_5b5ed477147d7',
        'label' => 'Jméno a příjmení',
        'name' => 'contact_full_name',
        'type' => 'text',
        'instructions' => 'Např. "Jan Novák"',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b5ed49d147d8',
        'label' => 'E-mail',
        'name' => 'contact_email',
        'type' => 'email',
        'instructions' => 'Např. "info@obchodiste.cz"',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_5b5ed4d3147d9',
        'label' => 'Telefon',
        'name' => 'contact_tel',
        'type' => 'text',
        'instructions' => 'Např. "+420603123456"',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b5ed50b147da',
        'label' => 'Fotografie obchodního zástupce',
        'name' => 'contact_photo',
        'type' => 'image',
        'instructions' => 'Doporučujeme nahrát fotografii o velikosti alespoň 100 x 100 px a zároveň ne větší než 500 x 500 px.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'library' => 'uploadedTo',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => 2,
        'mime_types' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'custom',
        ),
      ),
    ),
    'menu_order' => 1,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'field',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5b5ed585187a6',
    'title' => 'Podrobné informace',
    'fields' => array(
      array(
        'key' => 'field_5b5ed5a9ddd56',
        'label' => 'Hlavní kategorie',
        'name' => 'category',
        'type' => 'taxonomy',
        'instructions' => 'Zvolte si hlavní kategorii, do které spadá vaše firma.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'customtaxonomy',
        'field_type' => 'select',
        'allow_null' => 0,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'object',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5bff0ff2793a9',
        'label' => 'Vedlejší kategorie 1',
        'name' => 'minor_category_1',
        'type' => 'taxonomy',
        'instructions' => 'Zvolte si případnou vedlejší kategorii, do které spadá vaše firma.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'customtaxonomy',
        'field_type' => 'select',
        'allow_null' => 1,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'object',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5bff1029793aa',
        'label' => 'Vedlejší kategorie 2',
        'name' => 'minor_category_2',
        'type' => 'taxonomy',
        'instructions' => 'Zvolte si případnou další vedlejší kategorii, do které spadá vaše firma.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'taxonomy' => 'customtaxonomy',
        'field_type' => 'select',
        'allow_null' => 1,
        'add_term' => 0,
        'save_terms' => 0,
        'load_terms' => 0,
        'return_format' => 'object',
        'multiple' => 0,
      ),
      array(
        'key' => 'field_5b5ed640ddd57',
        'label' => 'Krátce o naší nabídce',
        'name' => 'short_about',
        'type' => 'wysiwyg',
        'instructions' => 'V krátkosti popište jaké zboží prodejcům nabízíte, jeho historii a případnou výjimečnost.',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5b5ed686ddd58',
        'label' => 'Co vám nabídneme?',
        'name' => 'services',
        'type' => 'checkbox',
        'instructions' => 'Vyberte si příznaky hlavních benefitů, které pro prodejce máte.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'Shoptet XML feed' => 'Shoptet XML feed',
          'Nonstop podpora' => 'Nonstop podpora',
          'Dárky k větším objednávkám' => 'Dárky k větším objednávkám',
          'Dropshipping' => 'Dropshipping',
        ),
        'allow_custom' => 1,
        'save_custom' => 0,
        'default_value' => array(
        ),
        'layout' => 'horizontal',
        'toggle' => 0,
        'return_format' => 'value',
      ),
      array(
        'key' => 'field_5b5ed759ddd59',
        'label' => 'O naší firmě',
        'name' => 'about_company',
        'type' => 'wysiwyg',
        'instructions' => 'Představte potenciálním prodávajícím co nejlépe historii a zajímavosti o vaší firmě.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_5b5ed775ddd5a',
        'label' => 'O našich produktech',
        'name' => 'about_products',
        'type' => 'wysiwyg',
        'instructions' => 'Podrobněji se rozepište o specifikách produktů, které prodejcům nabízíte.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 0,
        'delay' => 0,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'custom',
        ),
      ),
    ),
    'menu_order' => 2,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5b5f030dd7ca1',
    'title' => 'Galerie a video',
    'fields' => array(
      array(
        'key' => 'field_5b5f0597506c8',
        'label' => 'Galerie',
        'name' => 'gallery',
        'type' => 'gallery',
        'instructions' => 'Aby si zájemci udělali lepší obrázek o tom co nabízíte, vložte zde pár prezentačních snímků vašich produktů.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'min' => '',
        'max' => '',
        'insert' => 'append',
        'library' => 'uploadedTo',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => 2,
        'mime_types' => '',
        'return_format' => 'array',
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_5b5f05c8506c9',
        'label' => 'Video',
        'name' => 'video',
        'type' => 'oembed',
        'instructions' => 'Vložte video z YouTube nebo Vimeo obsahující informace o vašich produktech nebo firmě.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'width' => '',
        'height' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'custom',
        ),
      ),
    ),
    'menu_order' => 3,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));

endif;